GET http://localhost:8080/jwt/tokens
Authorization: Basic YWRtaW46e25vb3B9YWRtaW4= # admin:{noop}admin

###
GET http://localhost:8080/schedule/group/20209
Authorization: Bearer eyJraWQiOiJkM2YwZWEyMC1kZmQ1LTQyMWQtYTA2Zi0xMDYxNTc3M2ZjZDciLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTA4MDU3MSwiaWF0IjoxNzAxMDgwMjcxLCJqdGkiOiJkM2YwZWEyMC1kZmQ1LTQyMWQtYTA2Zi0xMDYxNTc3M2ZjZDciLCJhdXRob3JpdGllcyI6W119.S2c9LkgZ4wASKtzVGwNdVpbZKikg6CT96d8FfLnJCL8

###
POST http://localhost:8080/jwt/refresh
Authorization: Bearer eyJraWQiOiJkM2YwZWEyMC1kZmQ1LTQyMWQtYTA2Zi0xMDYxNTc3M2ZjZDciLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..unL3J7VwY5ywwDwm.WhLwsrNTi_k5qKAiEpNKbnQsCJIUp_Cut1GbEHfY0qrZK2PKJCCHtVLUh5smqHkGpEky8CAJYYjdgcrmkqGeph8MQNhOciWQr_7jjKmzqt_rfDGfVRCTIbIdXGijmcQ8CAer39PdauerbRhGTAo4EtYqnYaymUTtDBa4JAFs4QtA7VHuTsP_OW4.p18zGdYhEb8hv1pYJpf-8w

###
POST http://localhost:8080/jwt/logout
Authorization: Bearer eyJraWQiOiJkM2YwZWEyMC1kZmQ1LTQyMWQtYTA2Zi0xMDYxNTc3M2ZjZDciLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..unL3J7VwY5ywwDwm.WhLwsrNTi_k5qKAiEpNKbnQsCJIUp_Cut1GbEHfY0qrZK2PKJCCHtVLUh5smqHkGpEky8CAJYYjdgcrmkqGeph8MQNhOciWQr_7jjKmzqt_rfDGfVRCTIbIdXGijmcQ8CAer39PdauerbRhGTAo4EtYqnYaymUTtDBa4JAFs4QtA7VHuTsP_OW4.p18zGdYhEb8hv1pYJpf-8w
